version: "2"
checks:
    method-complexity:
        config:
            threshold: 15
exclude_paths:
    - ".nyc_output/"
    - node_modules/
    - test/
    - utils/
    - ".*"
    - "./**.json"
    - "./*.js"
